- hosts: localhost
  gather_facts:  no
  connection: local
  vars:
    cf_accountid: "{{ lookup('env', 'CF_ACCOUNTID') }}"
    cf_email: "{{ lookup('env', 'CF_EMAIL') }}"
    cf_apikey: "{{ lookup('env', 'CF_APIKEY') }}"
    cf_domain: "{{ lookup('env', 'CF_DOMAIN') }}"
    cf_workername: "{{ lookup('env', 'CF_WORKERNAME') }}"

  tasks:
    - name: Adding Cloudflare Worker Script
      uri:
        body: "addEventListener('fetch', event => { event.respondWith(fetch(event.request)) })"
        body_format: json
        url: "https://api.cloudflare.com/client/v4/accounts/{{ cf_accountid }}/workers/scripts/{{ cf_workername }}"
        method: PUT
        headers:
          Content-Type='application/javascript'
          X-Auth-Email="{{ cf_email }}"
          X-Auth-Key="{{ cf_apikey }}"