- hosts: localhost
  gather_facts:  no
  connection: local
  vars:
    cf_accountid: "{{ lookup('env', 'CF_ACCOUNTID') }}"
    cf_email: "{{ lookup('env', 'CF_EMAIL') }}"
    cf_apikey: "{{ lookup('env', 'CF_APIKEY') }}"
    cf_domain: "{{ lookup('env', 'CF_DOMAIN') }}"
    cf_workername: "{{ lookup('env', 'CF_WORKERNAME') }}"
    cf_route: "{{ lookup('env', 'CF_ROUTE') }}"  
  
  tasks:  
    - name: Detmine Zone ID
      include: get_zoneid.yml

    - name: Get all worker routes  
      include: get_routeid.yml
    
    - name: Delete Cloudflare Worker Route
      uri:
        url: "https://api.cloudflare.com/client/v4/zones/{{ cf_zoneid }}/workers/routes/{{ cf_routeid }}"
        method: DELETE
        headers:
          X-Auth-Email="{{ cf_email }}"
          X-Auth-Key="{{ cf_apikey }}"
      register: cf_response
    
    - name: Determine Zone ID
      include: get_zoneid.yml
    
#    - name: Show delete response
#      debug: var=cf_response